//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieGenre
    {
        public int MovieGenreID { get; set; }
        public int MovieID { get; set; }
        public int GenreID { get; set; }
    }
}
