//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Movie
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        [DisplayName("Year")]
        public Nullable<int> MovieYear { get; set; }
        [DisplayName("Media Type")]
        public string MovieType { get; set; }
        public string Location { get; set; }
        public string Director { get; set; }
        public string Plot { get; set; }
        public string Poster { get; set; }
        [DisplayName("Actors")]
        public string ActorString { get; set; }
        [DisplayName("Genres")]
        public string GenreString { get; set; }

        public static implicit operator Movie(MovieDetails v)
        {
            Movie movie = new Movie();
            movie.Title = v.Title;
            movie.MovieYear = v.Year;
            movie.Director = v.Director;
            movie.Plot = v.Plot;
            movie.Poster = v.Poster;
            movie.ActorString = v.Actors;
            movie.GenreString = v.Genre;

            return movie;
        }
    }
}
